employee/urls.py
from django.conf.urls import url
from .views import *

app_name = "employee"

urlpatterns = [

    url(r'^$', employee_view, name="index"),
    url(r'^login/$', login_view, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^profile/$', profile_view, name="profile"),
    url(r'^(?P<e_slug>[\w-]+)/$', detail_view, name="detail"),
    url(r'^(?P<e_slug>[\w-]+)/update/$', update_profile_view, name="update"),

]

projectmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view

urlpatterns = [

    url(r'^$', home_view, name='home'),

    #benim sayfaları
    url(r'^employee/', include('employee.urls')),
    url(r'^fault/', include('fault.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^salary/', include('salary.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^vote/', include('vote.urls')),
    url(r'^work/', include('work.urls')),

    url(r'^admin/', admin.site.urls),
]

task/urls.py
from django.conf.urls import url
from .views import *

app_name = "task"

urlpatterns = [

    url(r'^$', task_view, name="index"),
    url(r'^add/$', create_view, name="add"),
    url(r'^confirm/$', confirm_task_view, name="confirm"),
    url(r'^(?P<t_slug>[\w-]+)/work/$', task_work, name="work"),
    url(r'^(?P<t_slug>[\w-]+)/fault/$', task_fault, name="fault"),
    url(r'^(?P<t_slug>[\w-]+)/$', detail_view, name="detail"),
    url(r'^(?P<t_slug>[\w-]+)/update/$', update_view, name="update"),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from employee.models import Employee
from task.models import Task
from project.models import Project


# Create your views here.
def home_view(request):
    return render(request, 'home/index.html', {})


def pdf_view(request):
    if not request.user.is_authenticated():
        return redirect('home')

    employee_list = Employee.objects.all()
    task_list = Task.objects.all()
    project_list = Project.objects.all()

    context = {
        'employee_list': employee_list,
        'task_list': task_list,
        'project_list': project_list,
    }

    return render(request, "home/pdf.html", context)

from reportlab.pdfgen import canvas
from django.http import HttpResponse


def some_view(request):
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='home/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, "Hello world.")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()
    return response

templates/home/index.html
{% extends 'base.html' %}

{% block title %}
Project Manager | Home | Index
{% endblock %}

{% block body %}


    <div class="container">
        <div class="row">
            {% if not request.user.is_authenticated %}
                <div class="col-md-5"></div>
                <div class="col-md-2">
                    <br><br><br><br>

                    <div class="row container">
                        <a href="{% url 'employee:login' %}" class="btn btn-primary btn-lg">Login</a>
                    </div>
                </div>
            <div class="col-md-5"></div>
            {% else %}
                 <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="well">
                        <h1>{{ request.user.get_full_name }}</h1><br>
                        ana sayfa böle gözükçekbr <br>
                        burad araporlama kısmı olucak


                    </div>
                </div>
                <div class="col-md-1"></div>
            {% endif %}

        </div>
    </div>

{% endblock %}

templates/home/pdf.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}
Project Manager | Home | Pdf
{% endblock %}



{% block body %}

{# /project/{{ project.p_id }} #}

{#{% url 'detail' id=project.p_id %}#}

            {% if request.user.is_authenticated %}
                {% for project in project_list %}

                        name : {{ project.p_name }}
                        type : {{ project.p_type }}
                        begin : {{ project.p_begin }}
                        end : {{ project.p_end }}
                        manager : {{ project.p_manager.get_full_name }}



                {% endfor %}
            {% else %}
                 giriş yapılmaış
            {% endif %}



{% endblock %}