fault/urls.py
from django.conf.urls import url
from .views import *

app_name = "fault"

urlpatterns = [

    url(r'^$', fault_view, name="index"),

    url(r'^add/$', add_view, name="add"),
    url(r'^(?P<f_slug>[\w-]+)/$', detail_view, name="detail"),
    url(r'^(?P<f_slug>[\w-]+)/update/$', update_view, name="update"),

]

project/urls.py
from django.conf.urls import url
from .views import active_project_view, confirm_project_view, project_create, project_detail, project_update, project_vote, project_task

app_name = "project"
urlpatterns = [
    url(r'^$', active_project_view, name="index"),
    url(r'^create/$', project_create, name="create"),
    url(r'^confirm$', confirm_project_view, name="confirm"),
    url(r'^(?P<p_slug>[\w-]+)/vote/$', project_vote, name="vote"),
    url(r'^(?P<p_slug>[\w-]+)/$', project_detail, name="detail"),
    url(r'^(?P<p_slug>[\w-]+)/update/$', project_update, name="update"),
    url(r'^(?P<p_slug>[\w-]+)/task/$', project_task, name="task"),


]

projectmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view

urlpatterns = [

    url(r'^$', home_view, name='home'),

    #benim sayfaları
    url(r'^employee/', include('employee.urls')),
    url(r'^fault/', include('fault.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^salary/', include('salary.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^vote/', include('vote.urls')),
    url(r'^work/', include('work.urls')),

    url(r'^admin/', admin.site.urls),
]

salary/urls.py
from django.conf.urls import url
from .views import *

app_name = "salary"

urlpatterns = [

    url(r'^$', salary_view, name="index"),
    url(r'^add/$', add_view, name="add"),

]

task/urls.py
from django.conf.urls import url
from .views import *

app_name = "task"

urlpatterns = [

    url(r'^$', task_view, name="index"),
    url(r'^add/$', create_view, name="add"),
    url(r'^confirm/$', confirm_task_view, name="confirm"),
    url(r'^(?P<t_slug>[\w-]+)/work/$', task_work, name="work"),
    url(r'^(?P<t_slug>[\w-]+)/fault/$', task_fault, name="fault"),
    url(r'^(?P<t_slug>[\w-]+)/$', detail_view, name="detail"),
    url(r'^(?P<t_slug>[\w-]+)/update/$', update_view, name="update"),

]

work/urls.py
from django.conf.urls import url
from .views import *

app_name = "work"

urlpatterns = [

    url(r'^$', work_view, name="index"),
    url(r'^add/$', add_view, name="add"),

]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Project Manager{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="container">

    {% if request.user.is_authenticated %}
        {% include "header.html" %}
    {% endif %}


    {% block body %}

    {% endblock %}

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top " role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Project Manager</a>
        </div>

        <nav class="collapse navbar-collapse " role="navigation">



            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right ">

                <li><a href="{% url 'home' %}">Home</a></li>


                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Project
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'project:create' %}">Create</a></li>
                        <li><a href="{% url 'project:index' %}">Active</a></li>
                        <li><a href="{% url 'project:confirm' %}">Confirm</a></li>

                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Employee
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'employee:profile' %}">My Profile</a></li>
                        <li><a href="{% url 'employee:index' %}">List</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Fault
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'fault:index' %}">List</a></li>

                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Task
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'task:index' %}">Active</a></li>
                        <li><a href="{% url 'task:confirm' %}">Confirm</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Work
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'work:index' %}">List</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Salary
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'salary:add' %}">Add</a></li>
                        <li><a href="{% url 'salary:index' %}">Index</a></li>
                    </ul>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'employee:logout' %}" class="btn btn-danger">Logout</a>
                    </li>
                {% endif %}



            </ul>

        </nav>

    </div>
</nav>